from core.errors.odoo_exception import OdooException